version: "3"

services:
  mysql:
    container_name: mysql
    image: mysql:5.7
    network_mode: "host"
    ports:
    - "3306:3306"
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: "orm_bench"
    volumes:
    - ./data/mysql:/var/lib/mysql
    - ./my.cnf:/etc/mysql/conf.d/mysql_db.cnf
